# arrayの保存

In [2]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

#### 保存

In [4]:
np.save('my_arr', arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 読み込み

In [8]:
np.load('my_arr.npy')

array([0, 1, 2, 3, 4])

In [9]:
arr1 = np.load('my_arr.npy')

In [10]:
arr2 = np.arange(10)

#### zipで保存

In [11]:
np.savez('ziparr.npz',x=arr1,y=arr2)

In [12]:
arc_arr = np.load('ziparr.npz')

In [13]:
arc_arr

In [14]:
arc_arr['x']

array([0, 1, 2, 3, 4])

In [15]:
arc_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### テキスト形式で保存

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
np.savetxt('test.txt', arr, delimiter=',')

In [5]:
!cat test.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00


In [6]:
arr = np.loadtxt('test.txt', delimiter=',')

In [7]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])