In [1]:
import numpy as np

## numpy配列の計算

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

平方根

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

自然対数

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

ランダムな行列生成

In [6]:
A = np.random.randn(10)

In [7]:
B = np.random.randn(10)

In [9]:
A

array([-0.08965683,  1.07277289,  0.41540373,  3.21074914,  1.62492643,
       -0.73029199,  0.03715365,  0.93967682, -0.35226451, -0.96863536])

In [10]:
B

array([ 1.3613981 ,  1.16010048,  1.22678669, -0.96162312,  0.67182002,
       -0.52484575, -0.58588534, -0.27726794,  0.32837252, -0.71684823])

#### 行列の和

In [11]:
np.add(A, B)

array([ 1.27174128,  2.23287337,  1.64219042,  2.24912602,  2.29674645,
       -1.25513774, -0.5487317 ,  0.66240888, -0.02389198, -1.68548359])

#### 最大値

In [12]:
np.maximum(A,B)

array([ 1.3613981 ,  1.16010048,  1.22678669,  3.21074914,  1.62492643,
       -0.52484575,  0.03715365,  0.93967682,  0.32837252, -0.71684823])