In [4]:
import numpy as np

In [5]:
my_list1 = [1, 2, 3, 4]

In [6]:
my_list1

[1, 2, 3, 4]

In [7]:
my_arr1 = np.array(my_list1)

In [8]:
my_arr1

array([1, 2, 3, 4])

In [9]:
my_list2 = [5, 6, 7, 8]

In [10]:
my_list2

[5, 6, 7, 8]

In [11]:
my_lists = [my_list1, my_list2]

In [12]:
my_lists

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
my_arr = np.array(my_lists)

In [14]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### 行列の行と列数を出す

In [22]:
my_arr.shape

(2, 4)

#### 型を出す

In [24]:
my_arr.dtype

dtype('int64')

#### floatのゼロ埋め

In [18]:
np.zeros(2)

array([ 0.,  0.])

#### 1で穴埋めした行列を返却

In [19]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#### 空の行列を作成

In [20]:
np.empty((1, 2))

array([[ 0.,  0.]])

#### 単位行列

In [21]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5, 30, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])