In [5]:
import numpy as np

## numpyのarray生成

In [5]:
my_list1 = [1, 2, 3, 4]

In [6]:
my_list1

[1, 2, 3, 4]

In [7]:
my_arr1 = np.array(my_list1)

In [8]:
my_arr1

array([1, 2, 3, 4])

In [9]:
my_list2 = [5, 6, 7, 8]

In [10]:
my_list2

[5, 6, 7, 8]

In [11]:
my_lists = [my_list1, my_list2]

In [12]:
my_lists

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
my_arr = np.array(my_lists)

In [14]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### 行列の行と列数を出す

In [22]:
my_arr.shape

(2, 4)

#### 型を出す

In [24]:
my_arr.dtype

dtype('int64')

#### floatのゼロ埋め

In [18]:
np.zeros(2)

array([ 0.,  0.])

#### 1で穴埋めした行列を返却

In [19]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#### 空の行列を作成

In [20]:
np.empty((1, 2))

array([[ 0.,  0.]])

#### 単位行列

In [21]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5, 30, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

## numpyのarray計算

In [16]:
arr8_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [11]:
arr8_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### 掛け算

In [12]:
arr8_1 * arr8_1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

#### 引き算

In [13]:
arr8_1 - arr8_1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### スカラー値の割り算

In [14]:
1 / arr8_1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

#### べき乗

In [15]:
arr8_1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

#### 内積

In [18]:
np.dot(arr8_1.T, arr8_1)

array([[26, 32, 38, 44],
       [32, 40, 48, 56],
       [38, 48, 58, 68],
       [44, 56, 68, 80]])

## arrayの添字

In [17]:
arr9_1 = np.arange(0, 11)

In [18]:
arr9_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr9_1[4]

4

In [20]:
arr9_1[2:8]

array([2, 3, 4, 5, 6, 7])

In [21]:
arr9_1[0:5] = 120

In [22]:
arr9_1

array([120, 120, 120, 120, 120,   5,   6,   7,   8,   9,  10])

In [23]:
s_arr9_1 = arr9_1[2:5]

In [24]:
s_arr9_1[:]

array([120, 120, 120])

In [25]:
s_arr9_1[:] = 100

In [26]:
s_arr9_1

array([100, 100, 100])

In [27]:
arr9_1

array([120, 120, 100, 100, 100,   5,   6,   7,   8,   9,  10])

**sliceは参照のため、もとの配列も書き換わってしまう**

In [28]:
arr9_1 = np.arange(0, 11)

In [29]:
arr9_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**copy()を呼ぶことで参照ではなくコピーした配列作成**

In [30]:
arr9_1_copy = arr9_1.copy()

In [31]:
arr9_1_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr9_1_copy[:] = 99

In [33]:
arr9_1_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [34]:
arr9_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 2次元配列

In [35]:
arr9_2 = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [36]:
arr9_2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr9_2[1]

array([20, 25, 30])

In [38]:
arr9_2[1][1]

25

In [39]:
arr9_2[1, 1]

25

In [40]:
arr9_2[1:, 1:]

array([[25, 30],
       [40, 45]])

In [41]:
arr9_2[1:2, 0:1]

array([[20]])

In [43]:
arr9_2[1:3, 0:]

array([[20, 25, 30],
       [35, 40, 45]])

#### その他の例

In [44]:
arr9_3 = np.zeros((10, 10))

In [45]:
arr9_3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [46]:
arr9_3_length = arr9_3.shape[1]

In [47]:
arr9_3_length

10

In [49]:
for i in range(arr9_3_length):
    arr9_3[i] = i

In [50]:
arr9_3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [51]:
arr9_3[[2, 5, 7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [52]:
arr9_3[[5, 8, 2]]

array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]])

## 行列の扱い

In [6]:
arr10_1 = np.arange(9).reshape((3,3))

In [7]:
arr10_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 転置

In [8]:
arr10_1.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
arr10_1.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [11]:
arr10_1.shape

(3, 3)

In [12]:
arr10_1.transpose((0, 1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# 1軸と0軸を入れ替え
arr10_1.transpose((1, 0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

行と列を純粋に入れ替える場合

In [14]:
arr10_1.swapaxes(0, 1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])